#!/usr/bin/env bash

red="\e[31m"
grn="\e[32m"
ylw="\e[33m"
cyn="\e[36m"
blu="\e[34m"
prp="\e[35m"
bprp="\e[35;1m"
rst="\e[0m"

icon="$( ~/scripts/get_xres color2 )"
fg="$( ~/scripts/get_xres color7 )"

bat_status=""
bat_status=$( cat /sys/class/power_supply/BAT0/capacity )
charging_status=$( cat /sys/class/power_supply/BAT0/status )

health() {
	for i in {1..5}
	do
		if [[ $i -le $(( $bat_status/20 )) ]]; then
			echo -ne "${red}♥${rst}"
		else
			echo -ne "${ylw}♥${rst}"
		fi
	done
	echo
}

if [[ "$charging_status" == "Charging" ]]; then
    echo -ne "+$bat_status%"
else
    echo -ne "$bat_status%"
fi
