#!/usr/bin/env python

import sys
import os
from os.path import expanduser


home = expanduser("~")

try:
    if len(sys.argv) < 2:
        raise ValueError("Not enough arguments")

    for i in range(len(sys.argv) - 1):
        os.popen("curl -F'file=@" + sys.argv[i + 1] + "' https://0x0.st | xclip -selection clipboard")
        notification = "notify-send 'Uploaded' " + sys.argv[i + 1]
        link = os.popen("xclip -selection clipboard -o").read()
        with open(home + '/scripts/logs.txt', 'at') as f:
            f.write(sys.argv[i + 1])
            f.write(' - ')
            f.write(str( link ))
            f.write('\n')
        os.popen(notification)

except ValueError as ve:
    print(ve)
