#!/usr/bin/env bash

fg="$( ~/scripts/get_xres color7 )"
icon="$( ~/scripts/get_xres color2 )"

while getopts idq options
do
	case $options in
		i)
			amixer sset Master 2%+
			;;

		d)
			amixer sset Master 2%-
			;;
		q)
			cur_vol=$(  amixer sget Master | awk -F"[][]" '/dB/ { print $2 }'  )
			echo "%{F$icon} %{F$fg}$cur_vol"
			;;
	esac
done
