#!/usr/bin/env bash

#    ____  ___)                               
#   (, /   /          /)         /)     /)    
#     /---/   _  __  (/_ _  _/_ //     // _/_ 
#  ) /   (___(/_/ (_/_) /_)_(__(/_(_(_/(_ (__ 
# (_/                                /)       
#                                   (/        


hc() {
    cmds="$cmds , $@"
}

hc emit_hook reload
xsetroot -solid '#222222'
hc pad 0 28 0 0
hc keyunbind --all

# startup execs
xmodmap ~/.speedswapper
pkill compton
compton &
killall dunst
dunst -conf /home/icyphox/.config/dunst/dunstrc &
xrdb .Xresources
pkill polybar
polybar top &
redshift -O 4500K
xinput --set-prop 11 "libinput Accel Speed" 0.7
urxvtd -q -f -o &
nitrogen --set-color=#04191C --set-zoom-fill ~/dotfiles/images/wallpaper.png

Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-c close_and_remove
hc keybind $Mod-c       close
hc keybind $Mod-Return spawn ${TERMINAL:-urxvtc} # use your $TERMINAL with xterm as fallback

hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right


hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right


# frame bindings
hc keybind $Mod-u chain .-. split bottom 0.5 .-. focus down
hc keybind $Mod-o chain .-. split right  0.5 .-. focus right

hc keybind $Mod-Shift-u chain .-. split bottom 0.5 .-. shift_edge down
hc keybind $Mod-Shift-o chain .-. split right  0.5 .-. shift_edge right

hc keybind $Mod-Control-space split explode


# resize bindings
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep


tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" chain .-. move_index "$i" .-. use_index "$i"
    fi
done

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Shift-period chain .-. move_index +1 .-. use_index +1
hc keybind $Mod-Shift-comma chain .-. move_index -1 .-. use_index -1

hc keybind $Mod-x remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-w set_layout max
hc keybind $Mod-g set_layout grid
hc keybind $Mod-v set_layout vertical
hc keybind $Mod-a set_layout horizontal
hc keybind $Mod-Shift-space cycle_layout
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize


hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-d spawn rofi -show run


hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#61C46A'
hc set frame_border_normal_color '#313131'
hc set frame_bg_normal_color '#292a44'
hc set frame_bg_active_color '#292a44'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_active_opacity 1
hc set frame_normal_opacity 1
hc set frame_transparent_width 2
hc set frame_gap 0

hc attr theme.active.color '#123a2d'
hc attr theme.normal.color '#122426'
hc attr theme.urgent.color '#fffdff'
hc attr theme.inner_width 0
hc attr theme.inner_color '#fffdff'
hc attr theme.border_width 0
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#020c0d'
hc attr theme.active.outer_color '#fffdff'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 8
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0


hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class~'[Pp]olybar' manage=off
hc rule class~'[Ii]nkscape' pseudotile=on

hc unlock

#herbstclient set tree_style '╾│ ├└╼─┐'
herbstclient set tree_style '╾│ ├╰╼─╮'
#herbstclient set tree_style '*| +`>-.'
'`'
# ╭╰
herbstclient chain $cmds &
